blog/urls.py
"""
File name: urls.py.

Name: Inventory App

Description: With this web application you can do the inventory of all
             the material of your laboratory or business. You can also
             place orders but this form is case-specific. Moreover,
             you can track all your manufacturing procedures such as
             wafer fabrication in this case.

Copyright (C) 2017  Heriberto J. Díaz Luis-Ravelo

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

Email: heriberto.diazluis@gmail.com
"""

from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    # #################### HOME #################### #
    url(r'^$', views.home, name='home'),

    # #################### SIGN UP #################### #
    url(r'^accounts/signup/$', views.signup, name='signup'),
    url(r'^accounts/signin/$', views.signin, name='signin'),
    url(r'^accounts/signout/$', views.signout, name='signout'),

    # #################### DOWNLOAD #################### #
    url(r'^download/$', views.download_list, name='download_list'),
    url(r'^download/computing/$', views.download_computing, name='download_computing'),
    url(r'^download/electronic/$', views.download_electronic, name='download_electronic'),
    url(r'^download/optic/$', views.download_optic, name='download_optic'),
    url(r'^download/chemical/$', views.download_chemical, name='download_chemical'),
    url(r'^download/biological/$', views.download_biological, name='download_biological'),
    url(r'^download/instrumentation/$', views.download_instrumentation, name='download_instrumentation'),

    # #################### INVENTORY #################### #
    url(r'^inventory/$', views.inventory_list, name='inventory_list'),
    url(r'^inventory/(?P<pk>[0-9]+)/$', views.inventory_detail, name='inventory_detail'),
    url(r'^inventory/new/$', views.inventory_new, name='inventory_new'),
    url(r'^inventory/(?P<pk>[0-9]+)/edit/$', views.inventory_edit, name='inventory_edit'),
    url(r'^inventory/(?P<pk>\d+)/remove/$', views.inventory_remove, name='inventory_remove'),

    # #################### COMPUTING #################### #
    url(r'^computing/$', views.computing_list, name='computing_list'),
    url(r'^computing/search/$', views.computing_search, name='computing_search'),
    url(r'^computing/(?P<pk>[0-9]+)/$', views.computing_detail, name='computing_detail'),
    url(r'^computing/new/$', views.computing_new, name='computing_new'),
    url(r'^computing/(?P<pk>[0-9]+)/edit/$', views.computing_edit, name='computing_edit'),
    url(r'^computing/(?P<pk>\d+)/remove/$', views.computing_remove, name='computing_remove'),

    # #################### ELECTRONIC #################### #
    url(r'^electronic/component/$', views.electronic_list_type_components,
        name='electronic_list_type_components'),
    url(r'^electronic/component/(?P<pk>[0-9]+)/$', views.electronic_list,
        name='electronic_list'),
    url(r'^electronic/search/$', views.electronic_search, name='electronic_search'),
    url(r'^electronic/(?P<pk>[0-9]+)/$', views.electronic_detail, name='electronic_detail'),
    url(r'^electronic/new/$', views.electronic_new, name='electronic_new'),
    url(r'^electronic/(?P<pk>[0-9]+)/edit/$', views.electronic_edit, name='electronic_edit'),
    url(r'^electronic/(?P<pk>\d+)/remove/$', views.electronic_remove, name='electronic_remove'),

    # #################### OPTIC #################### #
    url(r'^optic/component/$', views.optic_list_type_optic, name='optic_list_type_optic'),
    url(r'^optic/component/(?P<pk>[0-9]+)/$', views.optic_list, name='optic_list'),
    url(r'^optic/search/$', views.optic_search, name='optic_search'),
    url(r'^optic/(?P<pk>[0-9]+)/$', views.optic_detail, name='optic_detail'),
    url(r'^optic/new/$', views.optic_new, name='optic_new'),
    url(r'^optic/(?P<pk>[0-9]+)/edit/$', views.optic_edit, name='optic_edit'),
    url(r'^optic/(?P<pk>\d+)/remove/$', views.optic_remove, name='optic_remove'),

    # #################### CHEMICAL ##################### #
    url(r'^chemical/component/$', views.chemical_list_type_chemical,
        name='chemical_list_type_chemical'),
    url(r'^chemical/component/(?P<pk>[0-9]+)/$', views.chemical_list,
        name='chemical_list'),
    url(r'^chemical/search/$', views.chemical_search, name='chemical_search'),
    url(r'^chemical/(?P<pk>[0-9]+)/$', views.chemical_detail, name='chemical_detail'),
    url(r'^chemical/new/$', views.chemical_new, name='chemical_new'),
    url(r'^chemical/(?P<pk>[0-9]+)/edit/$', views.chemical_edit, name='chemical_edit'),
    url(r'^chemical/(?P<pk>\d+)/remove/$', views.chemical_remove, name='chemical_remove'),
    url(r'^chemical/chemicalToNotRegistered/$', views.chemical_supplierToNotRegistered,
        name='chemical_supplierToNotRegistered'),

    # #################### BIOLOGICAL ##################### #
    url(r'^biological/component/$', views.biological_list_type_biological,
        name='biological_list_type_biological'),
    url(r'^biological/component/(?P<pk>[0-9]+)/$', views.biological_list, name='biological_list'),
    url(r'^biological/search/$', views.biological_search, name='biological_search'),
    url(r'^biological/(?P<pk>[0-9]+)/$', views.biological_detail, name='biological_detail'),
    url(r'^biological/new/$', views.biological_new, name='biological_new'),
    url(r'^biological/(?P<pk>[0-9]+)/edit/$', views.biological_edit, name='biological_edit'),
    url(r'^biological/(?P<pk>\d+)/remove/$', views.biological_remove, name='biological_remove'),
    url(r'^biological/biologicalToNotRegistered/$', views.biological_supplierToNotRegistered,
        name='biological_supplierToNotRegistered'),

    # #################### INSTRUMENTATION #################### #
    url(r'^instrumentation/component/$', views.instrumentation_list_type,
        name='instrumentation_list_type'),
    url(r'^instrumentation/component/(?P<pk>[0-9]+)/$', views.instrumentation_list,
        name='instrumentation_list'),
    url(r'^instrumentation/search/$', views.instrumentation_search, name='instrumentation_search'),
    url(r'^instrumentation/(?P<pk>[0-9]+)/$', views.instrumentation_detail,
        name='instrumentation_detail'),
    url(r'^instrumentation/new/$', views.instrumentation_new, name='instrumentation_new'),
    url(r'^instrumentation/(?P<pk>[0-9]+)/edit/$', views.instrumentation_edit,
        name='instrumentation_edit'),
    url(r'^instrumentation/(?P<pk>\d+)/remove/$', views.instrumentation_remove,
        name='instrumentation_remove'),

    # #################### CONSUMABLE #################### #
    url(r'^consumable/$', views.consumable_list, name='consumable_list'),
    url(r'^consumable/search/$', views.consumable_search, name='consumable_search'),
    url(r'^consumable/(?P<pk>[0-9]+)/$', views.consumable_detail, name='consumable_detail'),
    url(r'^consumable/new/$', views.consumable_new, name='consumable_new'),
    url(r'^consumable/(?P<pk>[0-9]+)/edit/$', views.consumable_edit, name='consumable_edit'),
    url(r'^consumable/(?P<pk>\d+)/remove/$', views.consumable_remove, name='consumable_remove'),

    # #################### OTHERS #################### #
    # This is not active.
    # url(r'^others/$', views.others_list, name='others_list'),
    # url(r'^others/(?P<pk>[0-9]+)/$', views.others_detail, name='others_detail'),
    # url(r'^others/new/$', views.others_new, name='others_new'),
    # url(r'^others/(?P<pk>[0-9]+)/edit/$', views.others_edit, name='others_edit'),
    # url(r'^others/(?P<pk>\d+)/remove/$', views.others_remove, name='others_remove'),

    # #################### ORDER #################### #
    url(r'^order/$', views.order_list, name='order_list'),
    url(r'^order/search/$', views.order_search, name='order_search'),
    url(r'^order/detail/(?P<pk>[0-9]+)/$', views.order_detail, name='order_detail'),
    url(r'^order/new/$', views.order_new, name='order_new'),
    # url(r'^order/new/(?P<pk>[0-9]+)/$', views.order_new_next, name='order_new_next'),
    url(r'^order/(?P<pk>[0-9]+)/edit/$', views.order_edit, name='order_edit'),
    url(r'^order/(?P<pk>\d+)/remove/$', views.order_remove, name='order_remove'),
    url(r'^order/(?P<pk>\d+)/send/$', views.order_send_email, name='order_send_email'),
    url(r'^order/(?P<pk>\d+)/notify/$', views.order_notify, name='order_notify'),
    url(r'^order/(?P<pk>\d+)/upload/$', views.order_add_file, name='order_add_file'),

    # #################### SUPPLIER #################### #
    url(r'^supplier/$', views.supplier_list, name='supplier_list'),
    url(r'^supplier/search/$', views.supplier_search, name='supplier_search'),
    url(r'^supplier/(?P<pk>[0-9]+)/$', views.supplier_detail, name='supplier_detail'),
    url(r'^supplier/new/$', views.supplier_new, name='supplier_new'),
    url(r'^supplier/(?P<pk>[0-9]+)/edit/$', views.supplier_edit, name='supplier_edit'),
    url(r'^supplier/(?P<pk>\d+)/remove/$', views.supplier_remove, name='supplier_remove'),

    # #################### RUN #################### #
    url(r'^run/$', views.run_list, name='run_list'),
    # url(r'^run/(?P<pk>[0-9]+)/$', views.run_chip_list, name='run_chip_list'),
    url(r'^run/(?P<pk>[0-9]+)/edit/$', views.run_edit, name='run_edit'),
    url(r'^run/(?P<pk>[0-9]+)/$', views.wafer_list, name='wafer_list'),

    # #################### WAFER #################### #

blog/views/chip.py
"""
File name: chip.py.

Name: Inventory App

Description: With this web application you can do the inventory of all
             the material of your laboratory or business. You can also
             place orders but this form is case-specific. Moreover,
             you can track all your manufacturing procedures such as
             wafer fabrication in this case.

Copyright (C) 2017  Heriberto J. Díaz Luis-Ravelo

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

Email: heriberto.diazluis@gmail.com
"""

from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from blog.models import Run, Chip, Wafer, Name_Waveguide
from blog.forms import RunForm, WaferForm, ChipForm, WaveguideForm


@login_required(login_url='/accounts/signin/')
def chip_list(request):
    """
    Chip_list function docstring.

    This function shows the list of chips that are stored in this web app and they are ordered by
    creation date.

    @param request: HTML request page.

    @return: list of chips.
    """
    chips = Chip.objects.filter(created_date__lte=timezone.now()).order_by('created_date')

    return render(request, 'blog/chip_list.html', {'chips': chips})


@login_required(login_url='/accounts/signin/')
def chip_detail(request, pk):
    """
    Chip_detail function docstring.

    This function shows the information of a chip.

    @param request: HTML request page.

    @param pk: primary key of the chip.

    @return: one chip.

    @raise 404: chip does not exists.
    """
    chip = get_object_or_404(Chip, pk=pk)
    runback = False
    waferback = True

    return render(request, 'blog/chip_detail.html', {'chip': chip, 'waferPK': chip.wafer.pk,
                                                     'runback': runback, 'waferback': waferback})


@login_required(login_url='/accounts/signin/')
def chip_detail_exist(request, pk):
    """
    Chip_detail_exist function docstring.

    This function shows the information of a chip when a chip is created but this already exists.

    @param request: HTML request page.

    @param pk: primary key of the chip.

    @return: one chip.

    @raise 404: chip does not exists.
    """
    chip = get_object_or_404(Chip, pk=pk)

    return render(request, 'blog/chip_detail_exist.html', {'chip': chip})


@login_required(login_url='/accounts/signin/')
def chip_new(request):
    """
    Chip_new function docstring.

    This function shows the form to create a new chip. This function uses 3 forms to create a new
    chip (Run form, Wafer form and Chip form), moreover, when the form is completed, this function
    search if the run or wafer or chip already exists.

    @param request: HTML request page.

    @return: First time, this shows the form to a new chip. If the form is completed and the run or
    wafer or chip does not exists, return the details of this new chip.
    """
    if request.method == "POST":
        runForm = RunForm(request.POST, prefix='run')
        waferForm = WaferForm(request.POST, prefix='wafer')
        chipForm = ChipForm(request.POST, prefix='chip')
        # waveguideForm = WaveguideForm(request.POST, prefix='waveguide')
        if runForm.is_valid():
            run = runForm.save(commit=False)
            run_ex = Run.objects.get(run=run.run)
            # print(run)
            if not run_ex:
                # print(run_ex)
                run.save()
            else:
                run = run_ex
        if waferForm.is_valid():
            wafer = waferForm.save(commit=False)
            wafer_ex = Wafer.objects.get(wafer=wafer.wafer, run=run)
            # print(wafer)
            if not wafer_ex:
                # print(wafer_ex)
                wafer.run = run
                wafer.save()
            else:
                wafer = wafer_ex
        if chipForm.is_valid():
            chip = chipForm.save(commit=False)
            chip_ex = Chip.objects.get(chip=chip.chip, wafer=wafer, run=run)
            # print(chip)
            if not chip_ex:
                # print(chip_ex)
                chip.run = run
                chip.wafer = wafer
                chip.save()
                return redirect('blog:chip_detail', pk=chip.pk)
            else:
                chip = chip_ex
                return redirect('blog:chip_detail_exist', pk=chip.pk)
    else:
        runForm = RunForm(prefix='run')
        waferForm = WaferForm(prefix='wafer')
        chipForm = ChipForm(prefix='chip')
        # waveguideFrom = WaveguideForm(prefix='waveguide')
    return render(request, 'blog/chip_edit.html', {'runForm': runForm, 'waferForm': waferForm,
                                                   'chipForm': chipForm})


@login_required(login_url='/accounts/signin/')
def chip_edit(request, pk):
    """
    Chip_edit function docstring.

    This function shows the form to modify a chip.

    @param request: HTML request page.

    @param pk: primary key of the chip to modify.

    @return: First time, this shows the form to edit the chip information. If the form is
    completed, return the details of this chip.

    @raise 404: chip does not exists.
    """
    chip = get_object_or_404(Chip, pk=pk)
    if request.method == "POST":
        form = ChipForm(data=request.POST, instance=chip)
        if form.is_valid():
            chip = form.save(commit=False)
            chip.save()
            return redirect('blog:chip_detail', pk=chip.pk)
    else:
        runForm = RunForm(instance=chip.run)
        waferForm = WaferForm(instance=chip.wafer)
        chipForm = ChipForm(instance=chip)
    return render(request, 'blog/chip_edit.html', {'runForm': runForm, 'waferForm': waferForm,
                                                   'chipForm': chipForm})


@login_required(login_url='/accounts/signin/')
def chip_remove(request, pk):
    """
    Chip_remove function docstring.

    This function removes a chip.

    @param request: HTML request page.

    @param pk: primary key of the chip to remove.

    @return: list of chips.

    @raise 404: chip does not exists.
    """
    chip = get_object_or_404(Chip, pk=pk)
    wafer_id = chip.wafer
    chip.delete()
    return redirect('blog:wafer_chip_list', pk=wafer_id)


@login_required(login_url='/accounts/signin/')
def chip_waveguide_new(run, wafer, chip):
    """
    Chip_waveguide_new function docstring.

    This function creates all waveguides of a chip. This function uses a forms to create the new
    waveguides (Waveguide form).

    @param run: primary key of the run.
    @param wafer: primary key of the wafer.
    @param chip: primary key of the chip.
    """
    waveguideName = Name_Waveguide.objects.all()
    # print(waveguideName)

    for waveguide in waveguideName:
        # print(waveguide.name)
        waveguideForm = WaveguideForm()
        newWaveguide = waveguideForm.save(commit=False)
        newWaveguide.run = run
        newWaveguide.wafer = wafer
        newWaveguide.chip = chip
        newWaveguide.waveguide = waveguide
        newWaveguide.name = waveguide.name
        # print(newWaveguide)
        newWaveguide.save()

blog/templates/blog/base_computing.html
<!doctype html>
{% load static %}

<!-- ***********************************************************************************************
    This HTML page is used as a base page to create similar pages of the Computing category.
************************************************************************************************ -->

<html>
    <head>

        <title>Computing</title>

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

        <!-- <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css"> -->
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/blog.css' %}">

    </head>
    <body>

        <!-- ***************************************************************************************
            This line includes the navigation bar.
        **************************************************************************************** -->
        {% include 'blog/navbar.html' %}

        <div class="page-header">

            <!-- ***********************************************************************************
                This part verifies if the username is logged in. If not, this shows an image to
                indicate that the username is not logged in.
            ************************************************************************************ -->
            {% if user.is_authenticated %}
                <a href="{% url 'blog:computing_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                {% if backList %}
                    <a href="{% url 'blog:computing_list' %}" class="top-menu"><span class="glyphicon glyphicon-chevron-left"></span></a>
                {% endif %}
                <div class="top-menu col-md-2">
                    <form id="searchform" action="{% url 'blog:computing_search' %}" method="get" accept-charset="utf-8">
                        <div id="custom-search-input">
                            <div class="input-group col-md-12">
                                <input type="text" class=" search-query form-control" name="searchfield" placeholder="Search" />
                                <span class="input-group-btn">
                                    <button class="btn btn-secondary" type="button">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
            {% else %}
                <a href="{% url 'blog:signin' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1><a href="{% url 'blog:computing_list' %}">Computing</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-12">

                <!-- *******************************************************************************
                    Contents of the page.
                ******************************************************************************** -->
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
        <script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="{% static 'js/navbarAction.js' %}"></script>
        <script src="{% static 'js/showHide_v2.js' %}"></script>
    </body>
</html>

blog/templates/blog/base_supplier.html
<!doctype html>
{% load static %}

<!-- ***********************************************************************************************
    This HTML page is used as a base page to create similar pages of the Computing category.
************************************************************************************************ -->

<html>
    <head>

        <title>Supplier</title>

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

        <!-- <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css"> -->
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'css/blog.css' %}">

    </head>
    <body>

        <!-- ***************************************************************************************
            This line includes the navigation bar.
        **************************************************************************************** -->
        {% include 'blog/navbar.html' %}

        <div class="page-header">

            <!-- ***********************************************************************************
                This part verifies if the username is logged in. If not, this shows an image to
                indicate that the username is not logged in.
            ************************************************************************************ -->
            {% if user.is_authenticated %}
                <a href="{% url 'blog:supplier_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                {% if backList %}
                    <a href="{% url 'blog:supplier_list' %}" class="top-menu"><span class="glyphicon glyphicon-chevron-left"></span></a>
                {% endif %}
                <div class="top-menu col-md-2">
                    <form id="searchform" action="{% url 'blog:supplier_search' %}" method="get" accept-charset="utf-8">
                        <div id="custom-search-input">
                            <div class="input-group col-md-12">
                                <input type="text" class=" search-query form-control" name="searchfield" placeholder="Search" />
                                <span class="input-group-btn">
                                    <button class="btn btn-secondary" type="button">
                                        <span class="glyphicon glyphicon-search"></span>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
            {% else %}
                <a href="{% url 'blog:signin' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1><a href="{% url 'blog:supplier_list' %}">Supplier</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-12">

                <!-- *******************************************************************************
                    Contents of the page.
                ******************************************************************************** -->
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
        <script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="{% static 'js/navbarAction.js' %}"></script>
        <script src="{% static 'js/showHide_v2.js' %}"></script>
    </body>
</html>

blog/templates/blog/element_list.html
{% extends 'blog/base_inventory.html' %}

{% block content %}
    <div class="element">
        <h1><a href="{% url 'blog:computing_list' %}">Computing</a></h1>
        <h1><a href="{% url 'blog:electronic_list' %}">Electronic</a></h1>
        <h1><a href="{% url 'blog:optic_list' %}">Optic</a></h1>
        <h1><a href="{% url 'blog:chemical_list' %}">Chemical</a></h1>
        <h1><a href="{% url 'blog:biological_list' %}">Biological</a></h1>
        <h1><a href="{% url 'blog:instrumentation_list' %}">Instrumentation</a></h1>
    </div>
{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base_home.html' %}

{% block content %}
    <div class="col-md-5">
        <div class="inventory">
            <h1><a href="{% url 'blog:inventory_list' %}">Inventory</a></h1>
                <h2><a class="inventory-secondCol" href="{% url 'blog:computing_list' %}">Computing</a></h2>
                <h2><a class="inventory-secondCol" href="{% url 'blog:electronic_list_type_components' %}">Electronic</a></h2>
                <h2><a class="inventory-secondCol" href="{% url 'blog:optic_list_type_optic' %}">Optics</a></h2>
                <h2><a class="inventory-secondCol" href="{% url 'blog:chemical_list_type_chemical' %}">Chemical</a></h2>
                <h2><a class="inventory-secondCol" href="{% url 'blog:biological_list_type_biological' %}">Biological</a></h2>
                <h2><a class="inventory-secondCol" href="{% url 'blog:instrumentation_list_type' %}">Instrumentation</a></h2>
                <h2><a class="inventory-secondCol" href="{% url 'blog:consumable_list' %}">Consumable</a></h2>
            <h1><a href="{% url 'blog:run_list' %}">RUN</a></h1>
            {% if user.is_staff %}
                <h1><a href="{% url 'blog:order_list' %}">Order</a></h1>
                <h1><a href="{% url 'blog:messages_list' %}" class="navbar-link">Messages</a></h1>
                <h1><a href="{% url 'blog:supplier_list' %}" class="navbar-link">Suppliers</a></h1>
                <h2><a href="{% url 'blog:chemical_supplierToNotRegistered' %}" class="navbar-link">Chemicals To Not Registered</a></h2>
                <h2><a href="{% url 'blog:biological_supplierToNotRegistered' %}" class="navbar-link">Biologicals To Not Registered</a></h2>
            {% endif %}
        </div>
    </div>
    {% if messagesInfo %}
        <div class="col-md-7">
            <div class="row" style="margin-bottom: 20px;">
                <div class="col-md-1">
                    <div class="buttonComment">
                        {% if user.is_authenticated %}
                            <a class="btn btn-default" href="{% url 'blog:messages_new' %}"><span class="glyphicon glyphicon-comment" title="New Comment"></span></a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row">
                {% for messageInfo in messagesInfo %}
                    <div class="col-md-11">
                        <div class="alert alert-info">
                            <strong>{{ messageInfo.author.first_name }}: </strong>{{ messageInfo.messageText }}
                        </div>
                    </div>
                    <div class="col-md-1">
                        <div class="button">
                            {% if user.is_authenticated and user == messageInfo.author %}
                                <a class="btn btn-default" href="{% url 'blog:messages_edit' pk=messageInfo.pk %}"><span class="glyphicon glyphicon-pencil" title="Edit Comment"></span></a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}

                {% if messagesInfo.has_other_pages %}
                    <div class="row">
                        <div class="col-md-6">
                            <div style="text-align: center;">
                                <nav aria-label="Page navigation">
                                    <ul class="pagination pagination-sm">
                                        {% if messagesInfo.has_previous %}
                                            <li><a href="?page={{ messagesInfo.previous_page_number }}">&laquo;</a></li>
                                        {% else %}
                                            <li class="disabled"><span>&laquo;</span></li>
                                        {% endif %}
                                        {% for i in messagesInfo.paginator.page_range %}
                                            {% if messagesInfo.number == i %}
                                                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if messagesInfo.has_next %}
                                            <li><a href="?page={{ messagesInfo.next_page_number }}">&raquo;</a></li>
                                        {% else %}
                                            <li class="disabled"><span>&raquo;</span></li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endblock content %}

blog/templates/blog/instrumentation_list_type.html
{% extends 'blog/base_instrumentation.html' %}

{% block content %}
    <div class="col-md-6">
        <div class="inventory">
            {% for instrumentation in instrumentations %}
                <h1><a href="{% url 'blog:instrumentation_list' pk=instrumentation.pk %}">{{ instrumentation.name }}</a></h1>
            {% endfor %}
        </div>
    </div>
{% endblock content %}